// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1 makearray()", "[example]")
{
	const int SIZE = 100;
	int numbers[SIZE];
	int cnt, result;
	result = 1;
	cnt = makearray(numbers);
	printout(numbers, cnt);
	result = (cnt > 0) ? 1 : 0;
	if ((cnt > 0))
	{
		for (int i = 0; i < cnt; i++)
			if ((numbers[i] <= 0) && (numbers[i] >= 100))
				result = 0;
	}
	INFO("The number of elements or array values are not valid\n");
	REQUIRE(result == 1);
}
// tests for exercise 2
TEST_CASE("Ex2 bubble() check", "[example]")
{
	const int SIZE = 100;
	int numbers[SIZE];
	int cnt, max, result;
	result = 1;
	cnt = makearray(numbers);
	printout(numbers, cnt);
	for (int i = 0; i < cnt; i++)
		if ((i == 0) || (max < numbers[i]))
			max = numbers[i];
	bubble(numbers, cnt);
	printout(numbers, cnt);

	INFO("The last element is not a greatest value after calling bubble() \n");
	REQUIRE(numbers[cnt - 1] == max);
}